### ISSUE TITLE
twenty seven

### ISSUE THREAD

**Issue by chromatic-aberration** [chazzireno/IEEE-FloatingPoint-shell#1]
i type twenty seven and it not work

fix pls

**Comment by strzeleckaktus** [comment]
i tried twenty six
not work too

**Comment by HubixD** [comment]
twenty five keine machen

**Comment by chazzireno** [comment]
You should type twenty and seven
Let me know if that works

**Comment by chromatic-aberration** [comment]
yes it does thank you
